### ISSUE TITLE
Silent Installer didn't install a working chmac

### ISSUE THREAD

**Issue by ghost** [wandersick/chmac#3]
I ran the ChMac-2.0.0.5_Silent_Installer.exe in a docker container to install ChMac. It installed with no errors reported.

When I run
    ChMac /l
I get the following error:

`#`  Error: No getmac.exe. Place one from Windows in "C:\Program Files (x86)\wandersick\ChMac\Data\3rdparty\LP"

Expected:
ChMac to return list ...

How to repair or other manual instructions ?

**Comment by ghost** [comment]
I see there is a read me in C:\Program Files (x86)\wandersick\ChMac\Data\3rdparty\LP" with additional install instructions.

**Comment by ChocoMachine** [comment]
Wouldn't it be better to just include these files in the installer ?

**Comment by ghost** [comment]
I am working on Server Core 2019... do the not installed files realy need to come from Windows_2013 or is that information out of date?
Also what is the reason the installer doesn't install these dependencies?
